worlds:
  cannon:
    entities:
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      maxentities:
        GHAST: 0
        ENDER_DRAGON: 0
        WITHER : 1
        total: 15
    physics:
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      materials:
      - SAND
      - ANVIL
      - GRAVEL
    redstone: 
      blocksbeforewarn: 2
      maxclockrepeat : 20
      maxredstonepercheck : 2000
    
      