name : PlotLimits
description : Prevent plot abusers and limit events that can happen in plots
author: Emerald_Explorer
main: com.oneshotmc.plotlimits.PlotLimits
version: ${version}
softdepend: [PlotSquared]
permissions:
  plotlimits.bypass.*:
    description: Give access to all bypass perms
    children:
      plotlimits.bypass.redstone: true
      plotlimits.bypass.entities: true
      plotlimits.bypass.physics: true
  plotlimits.admin:
    descriptionL have access to admin commands
    default: op
      
      